routes/admin.php
<?php

use Illuminate\Support\Facades\Route;



Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {
    /*authentication*/
    Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginController@login')->name('login');
        Route::post('login', 'LoginController@submit');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });
    /*authentication*/

    Route::group(['middleware' => ['admin']], function () {
        Route::get('/', 'SystemController@dashboard')->name('dashboard');
        Route::group(['prefix' => 'restaurants', 'as' => 'restaurants.'], function(){
            Route::group(['prefix' => 'request'], function(){
                Route::get('/', 'RestaurantController@requests')->name('request');
                Route::get('{restaurant}/update-status/{status}', 'RestaurantController@requestUpdateStatus')->name('request.update.status');
                Route::post('search', 'RestaurantController@requestSearch')->name('request.search');
            });
            
            Route::post('search', 'RestaurantController@search')->name('search');
        });
        Route::resource('restaurants', 'RestaurantController');
        
        Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
            Route::get('{category}/status/{status}', 'CategoryController@updateStatus')->name('status');
            Route::post('search', 'CategoryController@search')->name('search');
        });
        Route::resource('categories', 'CategoryController');

        Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
            Route::post('search', 'ProductController@search')->name('search');
            Route::get('{product}/update-status/{status}', 'ProductController@updateStatus')->name('update.status');
            Route::group(['prefix' => 'request'], function(){
                Route::get('/', 'ProductController@requests')->name('request');
                Route::get('{product}/update-status/{status}', 'ProductController@requestUpdateStatus')->name('request.update.status');
                Route::post('search', 'ProductController@requestSearch')->name('request.search');
            });
        });
        Route::resource('products', 'ProductController');

        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/', 'SystemController@settings')->name('show');
            Route::post('profile', 'SystemController@profile')->name('profile');
            Route::post('update-password', 'SystemController@updatePassword')->name('update.password');
            // Route::get('/get-restaurant-data', 'SystemController@restaurant_data')->name('get-restaurant-data');
        });

        // Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        //     Route::get('add', 'CategoryController@index')->name('add');
        //     Route::get('add-sub-category', 'CategoryController@sub_index')->name('add-sub-category');
        //     Route::get('add-sub-sub-category', 'CategoryController@sub_sub_index')->name('add-sub-sub-category');
        //     Route::post('store', 'CategoryController@store')->name('store');
        //     Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
        //     Route::post('update/{id}', 'CategoryController@update')->name('update');
        //     Route::post('store', 'CategoryController@store')->name('store');
        //     Route::get('status/{id}/{status}', 'CategoryController@status')->name('status');
        //     Route::delete('delete/{id}', 'CategoryController@delete')->name('delete');
        //     Route::post('search', 'CategoryController@search')->name('search');
        // });
        // Route::group(['prefix' => 'branch', 'as' => 'branch.'], function () {
        //     Route::get('add-new', 'BranchController@index')->name('add-new');
        //     Route::post('store', 'BranchController@store')->name('store');
        //     Route::get('edit/{id}', 'BranchController@edit')->name('edit');
        //     Route::post('update/{id}', 'BranchController@update')->name('update');
        //     Route::delete('delete/{id}', 'BranchController@delete')->name('delete');
        // });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['namespace' => 'Web', 'as' => 'web.'], function() {
    Route::group(['middleware' => 'guest'], function() {
        Route::get('/', 'LandingController@index')->name('landing');
        Route::get('restaurant/detail', 'RestaurantController@show')->name('restaurant.details');
        Route::get('search', 'SearchController@search')->name('search');
        Route::get('restaurant/search', 'SearchController@restaurantSearch')->name('restaurant.search');
//        Custom Code
//        end Code

        Route::get('aboutus', 'PageController@aboutUs')->name('aboutus');
        Route::get('privacy', 'PageController@privacy')->name('privacy');
        Route::get('faq', 'PageController@faq')->name('faq');
        Route::get('terms', 'PageController@terms')->name('terms');
    });

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/home', 'HomeController@index')->name('home');
    });
});

Route::get('category/{detail}','Custom\CategoryController@categoryDetail')->name('categoryDetail');
Route::get('product/{detail}','Custom\ProductController@productDetail')->name('productDetail');
Route::post('cart/{product_id}','Custom\CartController@cart')->name('productCart');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.app')

@section('title','Dashboard')

@push('css_or_js')

@endpush

@section('content')
    <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col-sm mb-2 mb-sm-0">
                    <h1 class="page-header-title">{{trans('messages.welcome')}}, {{auth('admin')->user()->f_name}}.</h1>
                    <p class="page-header-text">{{trans('messages.welcome_message')}}</p>
                </div>

                <div class="col-sm-auto">
                    <a class="btn btn-primary" href="{{ route('admin.restaurants.index')}}">
                        <i class="tio-premium-outlined mr-1"></i> {{trans('messages.restaurants')}}
                    </a>
                </div>
            </div>
        </div>
        <!-- End Page Header -->

        <!-- Card -->
        <div class="card card-body mb-3 mb-lg-5">
            <div class="row gx-lg-4">
                <div class="col-sm-6 col-lg-3">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{-- route('admin.orders.list',['pending']) --}}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.pending')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'pending'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-airdrop"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-3 column-divider-sm">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{-- route('admin.orders.list',['confirmed']) --}}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.confirmed')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'confirmed'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-checkmark-circle"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-3 column-divider-lg">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{-- route('admin.orders.list',['processing']) --}}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.processing')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'processing'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-running"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-3 column-divider-sm">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{-- route('admin.orders.list',['out_for_delivery']) --}}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.out_for_delivery')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'out_for_delivery'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-bike"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-body mb-3 mb-lg-5">
            <div class="row gx-lg-4">
                <div class="col-sm-6 col-lg-3 column-divider-sm">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{ route('admin.restaurants.index') }}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.restaurants')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'out_for_delivery'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-shop nav-icon"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div>
                <!-- <div class="col-sm-6 col-lg-3 column-divider-sm">
                    <div class="media" style="cursor: pointer" onclick="location.href='{{ route('admin.restaurants.index') }}'">
                        <div class="media-body">
                            <h6 class="card-subtitle">{{trans('messages.upcoming_restaurants')}}</h6>
                            <span class="card-title h3">0{{-- \App\Model\Order::where(['order_status'=>'out_for_delivery'])->count() --}}</span>
                        </div>
                        <span class="icon icon-sm icon-soft-secondary icon-circle ml-3">
                          <i class="tio-shop nav-icon"></i>
                        </span>
                    </div>
                    <div class="d-lg-none">
                        <hr>
                    </div>
                </div> -->
            </div>
        </div>
        <!-- End Card -->
    </div>
@endsection

@push('script')
    <script src="{{asset('assets/admin')}}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{asset('assets/admin')}}/vendor/chart.js.extensions/chartjs-extensions.js"></script>
    <script
        src="{{asset('assets/admin')}}/vendor/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.min.js"></script>
@endpush


@push('script_2')
    <script>
        // INITIALIZATION OF CHARTJS
        // =======================================================
        Chart.plugins.unregister(ChartDataLabels);

        $('.js-chart').each(function () {
            $.HSCore.components.HSChartJS.init($(this));
        });

        var updatingChart = $.HSCore.components.HSChartJS.init($('#updatingData'));

        // CALL WHEN TAB IS CLICKED
        // =======================================================
        $('[data-toggle="chart-bar"]').click(function (e) {
            let keyDataset = $(e.currentTarget).attr('data-datasets')

            if (keyDataset === 'lastWeek') {
                updatingChart.data.labels = ["Apr 22", "Apr 23", "Apr 24", "Apr 25", "Apr 26", "Apr 27", "Apr 28", "Apr 29", "Apr 30", "Apr 31"];
                updatingChart.data.datasets = [
                    {
                        "data": [120, 250, 300, 200, 300, 290, 350, 100, 125, 320],
                        "backgroundColor": "#377dff",
                        "hoverBackgroundColor": "#377dff",
                        "borderColor": "#377dff"
                    },
                    {
                        "data": [250, 130, 322, 144, 129, 300, 260, 120, 260, 245, 110],
                        "backgroundColor": "#e7eaf3",
                        "borderColor": "#e7eaf3"
                    }
                ];
                updatingChart.update();
            } else {
                updatingChart.data.labels = ["May 1", "May 2", "May 3", "May 4", "May 5", "May 6", "May 7", "May 8", "May 9", "May 10"];
                updatingChart.data.datasets = [
                    {
                        "data": [200, 300, 290, 350, 150, 350, 300, 100, 125, 220],
                        "backgroundColor": "#377dff",
                        "hoverBackgroundColor": "#377dff",
                        "borderColor": "#377dff"
                    },
                    {
                        "data": [150, 230, 382, 204, 169, 290, 300, 100, 300, 225, 120],
                        "backgroundColor": "#e7eaf3",
                        "borderColor": "#e7eaf3"
                    }
                ]
                updatingChart.update();
            }
        })


        // INITIALIZATION OF BUBBLE CHARTJS WITH DATALABELS PLUGIN
        // =======================================================
        $('.js-chart-datalabels').each(function () {
            $.HSCore.components.HSChartJS.init($(this), {
                plugins: [ChartDataLabels],
                options: {
                    plugins: {
                        datalabels: {
                            anchor: function (context) {
                                var value = context.dataset.data[context.dataIndex];
                                return value.r < 20 ? 'end' : 'center';
                            },
                            align: function (context) {
                                var value = context.dataset.data[context.dataIndex];
                                return value.r < 20 ? 'end' : 'center';
                            },
                            color: function (context) {
                                var value = context.dataset.data[context.dataIndex];
                                return value.r < 20 ? context.dataset.backgroundColor : context.dataset.color;
                            },
                            font: function (context) {
                                var value = context.dataset.data[context.dataIndex],
                                    fontSize = 25;

                                if (value.r > 50) {
                                    fontSize = 35;
                                }

                                if (value.r > 70) {
                                    fontSize = 55;
                                }

                                return {
                                    weight: 'lighter',
                                    size: fontSize
                                };
                            },
                            offset: 2,
                            padding: 0
                        }
                    }
                },
            });
        });
    </script>
@endpush