routes/admin.php
<?php

use Illuminate\Support\Facades\Route;



Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {
    /*authentication*/
    Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginController@login')->name('login');
        Route::post('login', 'LoginController@submit');
        Route::get('logout', 'LoginController@logout')->name('logout');
    });
    /*authentication*/

    Route::group(['middleware' => ['admin']], function () {
        Route::get('/', 'SystemController@dashboard')->name('dashboard');
        Route::group(['prefix' => 'restaurants', 'as' => 'restaurants.'], function(){
            Route::group(['prefix' => 'request'], function(){
                Route::get('/', 'RestaurantController@requests')->name('request');
                Route::get('{restaurant}/update-status/{status}', 'RestaurantController@requestUpdateStatus')->name('request.update.status');
                Route::post('search', 'RestaurantController@requestSearch')->name('request.search');
            });
            
            Route::post('search', 'RestaurantController@search')->name('search');
        });
        Route::resource('restaurants', 'RestaurantController');
        
        Route::group(['prefix' => 'categories', 'as' => 'categories.'], function(){
            Route::get('{category}/status/{status}', 'CategoryController@updateStatus')->name('status');
            Route::post('search', 'CategoryController@search')->name('search');
        });
        Route::resource('categories', 'CategoryController');

        Route::group(['prefix' => 'products', 'as' => 'products.'], function(){
            Route::post('search', 'ProductController@search')->name('search');
            Route::get('{product}/update-status/{status}', 'ProductController@updateStatus')->name('update.status');
            Route::group(['prefix' => 'request'], function(){
                Route::get('/', 'ProductController@requests')->name('request');
                Route::get('{product}/update-status/{status}', 'ProductController@requestUpdateStatus')->name('request.update.status');
                Route::post('search', 'ProductController@requestSearch')->name('request.search');
            });
        });
        Route::resource('products', 'ProductController');

        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/', 'SystemController@settings')->name('show');
            Route::post('profile', 'SystemController@profile')->name('profile');
            Route::post('update-password', 'SystemController@updatePassword')->name('update.password');
            // Route::get('/get-restaurant-data', 'SystemController@restaurant_data')->name('get-restaurant-data');
        });

        // Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        //     Route::get('add', 'CategoryController@index')->name('add');
        //     Route::get('add-sub-category', 'CategoryController@sub_index')->name('add-sub-category');
        //     Route::get('add-sub-sub-category', 'CategoryController@sub_sub_index')->name('add-sub-sub-category');
        //     Route::post('store', 'CategoryController@store')->name('store');
        //     Route::get('edit/{id}', 'CategoryController@edit')->name('edit');
        //     Route::post('update/{id}', 'CategoryController@update')->name('update');
        //     Route::post('store', 'CategoryController@store')->name('store');
        //     Route::get('status/{id}/{status}', 'CategoryController@status')->name('status');
        //     Route::delete('delete/{id}', 'CategoryController@delete')->name('delete');
        //     Route::post('search', 'CategoryController@search')->name('search');
        // });
        // Route::group(['prefix' => 'branch', 'as' => 'branch.'], function () {
        //     Route::get('add-new', 'BranchController@index')->name('add-new');
        //     Route::post('store', 'BranchController@store')->name('store');
        //     Route::get('edit/{id}', 'BranchController@edit')->name('edit');
        //     Route::post('update/{id}', 'BranchController@update')->name('update');
        //     Route::delete('delete/{id}', 'BranchController@delete')->name('delete');
        // });
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['namespace' => 'Web', 'as' => 'web.'], function() {
    Route::group(['middleware' => 'guest'], function() {
        Route::get('/', 'LandingController@index')->name('landing');
        Route::get('restaurant/detail', 'RestaurantController@show')->name('restaurant.details');
        Route::get('search', 'SearchController@search')->name('search');
        Route::get('restaurant/search', 'SearchController@restaurantSearch')->name('restaurant.search');
//        Custom Code
//        end Code

        Route::get('aboutus', 'PageController@aboutUs')->name('aboutus');
        Route::get('privacy', 'PageController@privacy')->name('privacy');
        Route::get('faq', 'PageController@faq')->name('faq');
        Route::get('terms', 'PageController@terms')->name('terms');
    });

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/home', 'HomeController@index')->name('home');
    });
});

Route::get('category/{detail}','Custom\CategoryController@categoryDetail')->name('categoryDetail');
Route::get('product/{detail}','Custom\ProductController@productDetail')->name('productDetail');
Route::post('cart/{product_id}','Custom\CartController@cart')->name('productCart');

resources/views/layouts/site/partials/_footer.blade.php
<footer class="footer" style="z-index: 99;">
    <div class="container">
        <!-- Foot Top Starts -->
        <div class="foot-top row">
            <!-- Foot Block Starts -->
            <div class="foot-block col-md-3 col-sm-12 col-xs-12">
                <h5 class="foot-tit">ABOUT US</h5>
                <div>
                    <a href="{{ route('web.aboutus') }}" class="foot-item">About us</a>
                    
                    <a href="{{ route('web.privacy') }}" class="foot-item">Privacy</a>

                </div>
            </div>
            <!-- Foot Block Ends -->
            <!-- Foot Block Starts -->
            <div class="foot-block col-md-3 col-sm-12 col-xs-12">
                <h5 class="foot-tit">SUPPORT</h5>
                <div>
                    <a href="{{ route('web.faq') }}" class="foot-item">FAQ</a>
                </div>
            </div>
            <!-- Foot Block Ends -->
            <!-- Foot Block Starts -->
            <div class="foot-block col-md-3 col-sm-12 col-xs-12">
                <h5 class="foot-tit">Terms and Conditions</h5>
                <div>
                    <a href="{{ route('web.terms') }}" class="foot-item">Terms and Conditions</a>




                </div>
            </div>
            <!-- Foot Block Ends -->
            <!-- Foot Block Starts -->
            <div class="foot-block col-md-3 col-sm-12 col-xs-12">
                <div class="foot-download-img-sec">

                    <a href="" class="foot-download-img" target="_blank"><img src="{{ asset('assets/site/img/play-store.png') }}"></a>
                </div>
                <div class="foot-download-img">
                    <a href="" class="foot-download-img" target="_blank"><img src="{{ asset('assets/site/img/android.png') }}"></a>

                </div>
            </div>
            <!-- Foot Block Ends -->
        </div>
        <!-- Foot Top Ends -->
        <!-- Foot Bottom Starts -->
        <div class="foot-btm row">
            <div class="col-md-4">
                <div class="foot-logo"><img src="{{ asset('assets/site/img/app/logo.png') }}">
                </div>
            </div>
            <div class="col-md-4 text-center">
                <p class="copy-txt">© 2021 site</p>
            </div>
            <div class="foot-social col-md-4 text-right">
                <a href="" target="_blank" class="foot-social-item"><i class="fa fa-facebook"></i></a>

                <a href="" target="_blank" class="foot-social-item"><i class="fa fa-instagram"></i></a>

            </div>
        </div>
        <!-- Foot Bottom Ends -->
    </div>
</footer>

resources/views/layouts/site/partials/_front-settings.blade.php
<div id="styleSwitcherDropdown" class="hs-unfold-content sidebar sidebar-bordered sidebar-box-shadow"
     style="width: 35rem;">
    <div class="card card-lg border-0 h-100">
        <div class="card-header align-items-start">
            <div class="mr-2">
                <h3 class="card-header-title">Front Builder</h3>
                <p>Customize your overview page layout. Choose the one that best fits your needs.</p>
            </div>

            <!-- Toggle Button -->
            <a class="js-hs-unfold-invoker btn btn-icon btn-xs btn-ghost-dark" href="javascript:;"
               data-hs-unfold-options='{
                  "target": "#styleSwitcherDropdown",
                  "type": "css-animation",
                  "animationIn": "fadeInRight",
                  "animationOut": "fadeOutRight",
                  "hasOverlay": true,
                  "smartPositionOff": true
                 }'>
                <i class="tio-clear tio-lg"></i>
            </a>
            <!-- End Toggle Button -->
        </div>

        <!-- Body -->
        <div class="card-body sidebar-scrollbar">
            <h4 class="mb-1">Layout skins <span id="js-builder-disabled" class="badge badge-soft-danger"
                                                style="opacity: 0">Disabled</span></h4>
            <p>3 kinds of layout skins to choose from.</p>

            <div class="row gx-2 mb-5">
                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="layoutSkinsRadio"
                                   id="layoutSkinsRadio1" checked value="default">
                            <label class="custom-checkbox-card-label" for="layoutSkinsRadio1">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/layouts-sidebar-default.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Default</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="layoutSkinsRadio"
                                   id="layoutSkinsRadio2" value="navbar-dark">
                            <label class="custom-checkbox-card-label" for="layoutSkinsRadio2">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/layouts-sidebar-dark.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Dark</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="layoutSkinsRadio"
                                   id="layoutSkinsRadio3" value="navbar-light">
                            <label class="custom-checkbox-card-label" for="layoutSkinsRadio3">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/layouts-sidebar-light.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Light</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->
            </div>
            <!-- End Row -->

            <h4 class="mb-1">Sidebar layout options</h4>
            <p>Choose between standard navigation sizing, mini or even compact with icons.</p>

            <div class="row gx-2 mb-5">
                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="sidebarLayoutOptions"
                                   id="sidebarLayoutOptions1" checked value="default">
                            <label class="custom-checkbox-card-label" for="sidebarLayoutOptions1">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/sidebar-default-classic.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Default</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="sidebarLayoutOptions"
                                   id="sidebarLayoutOptions2" value="navbar-vertical-aside-compact-mode">
                            <label class="custom-checkbox-card-label" for="sidebarLayoutOptions2">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/sidebar-compact.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Compact</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="sidebarLayoutOptions"
                                   id="sidebarLayoutOptions3" value="navbar-vertical-aside-mini-mode">
                            <label class="custom-checkbox-card-label" for="sidebarLayoutOptions3">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/sidebar-mini.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Mini</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->
            </div>
            <!-- End Row -->

            <h4 class="mb-1">Header layout options</h4>
            <p>Choose the primary navigation of your header layout.</p>

            <div class="row gx-2">
                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="headerLayoutOptions"
                                   id="headerLayoutOptions1" value="single">
                            <label class="custom-checkbox-card-label" for="headerLayoutOptions1">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/header-default-fluid.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Default (Fluid)</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="headerLayoutOptions"
                                   id="headerLayoutOptions2" value="single-container">
                            <label class="custom-checkbox-card-label" for="headerLayoutOptions2">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/header-default-container.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Default (Container)</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="headerLayoutOptions"
                                   id="headerLayoutOptions3" value="double">
                            <label class="custom-checkbox-card-label" for="headerLayoutOptions3">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/header-double-line-fluid.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Double line (Fluid)</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->

                <!-- Custom Radio -->
                <div class="col-4 text-center mt-2">
                    <div class="text-center">
                        <div class="custom-checkbox-card mb-2">
                            <input type="radio" class="custom-checkbox-card-input" name="headerLayoutOptions"
                                   id="headerLayoutOptions4" value="double-container">
                            <label class="custom-checkbox-card-label" for="headerLayoutOptions4">
                                <img class="custom-checkbox-card-img"
                                     src="{{asset('assets/admin')}}/svg/layouts/header-double-line-container.svg"
                                     alt="Image Description">
                            </label>
                            <span class="custom-checkbox-card-text">Double line (Container)</span>
                        </div>
                    </div>
                </div>
                <!-- End Custom Radio -->
            </div>
            <!-- End Row -->
        </div>
        <!-- End Body -->

        <!-- Footer -->
        <div class="card-footer">
            <div class="row gx-2">
                <div class="col">
                    <button type="button" id="js-builder-reset" class="btn btn-block btn-lg btn-white">
                        <i class="tio-restore"></i> Reset
                    </button>
                </div>
                <div class="col">
                    <button type="button" id="js-builder-preview" class="btn btn-block btn-lg btn-primary">
                        <i class="tio-visible"></i> Preview
                    </button>
                </div>
            </div>
            <!-- End Row -->
        </div>
        <!-- End Footer -->
    </div>
</div>

resources/views/layouts/site/partials/_header.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navgation-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="logo">
                        <a class="navbar-brand logoback" href="{{ route('web.landing') }}">
                            <img src="{{ asset('assets/site/img/app/logo.png') }}" height="50"
                                alt="" data-retina="true" class="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="collapse navbar-collapse" id="navgation-1">
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="nav navbar navbar-right addressform">
                                <li>

                                </li>
                            </ul>
                        </div>
                        <div class="col-md-12">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="{{ route('web.search') }}">
                                        <i class="ion-search"></i> Search
                                    </a>
                                </li>
                                <li>
                                    <a href=""><i class="ion-help-buoy"></i> Help</a>
                                </li>

                                @guest
                                    <li> <a href="javascript:void(0);" class="signinform">Login</a></li>
                                    @if (Route::has('register'))
                                        <li><a href="javascript:void(0);" class="active signupform">Register</a></li>
                                    @endif
                                @endguest

                                <li class="dropdown">
                                    <a href=""><span class="cart-count">0</span> Cart</a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                        aria-haspopup="true" aria-expanded="false">
                                        en
                                        <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="">ar</a></li>
                                    </ul>
                                </li>
                                @auth
                                    <li class="dropdown">
                                        <a id="" class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                            {{ Auth::user()->name }}
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="">
                                            <li>
                                                <a class="" href="{{ route('logout') }}"
                                                   onclick="event.preventDefault();
                                                                 document.getElementById('logout-form').submit();">
                                                    {{ __('Logout') }}
                                                </a>

                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                                    @csrf
                                                </form>
                                            </li>
                                        </ul>
                                    </li>
                                @endauth
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>